# Generated by Django 4.0.8 on 2023-01-01 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pg_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ', editable=False, length=8, max_length=16, prefix='', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('images', models.JSONField(blank=True, default=dict, null=True)),
                ('food_included', models.BooleanField(default=False)),
                ('owner', models.ManyToManyField(related_name='hostels', to='pg_admin.easypguser')),
            ],
            options={
                'db_table': 'hostels',
            },
        ),
        migrations.CreateModel(
            name='HostelType',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ', editable=False, length=8, max_length=16, prefix='', primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('TRIPLE_SHARING', 'TRIPLE_SHARING'), ('DOUBLE_SHARING', 'DOUBLE_SHARING'), ('SINGLE', 'SINGLE')], default='DOUBLE_SHARING', max_length=30)),
                ('price', models.PositiveIntegerField()),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_types', to='customer.hostel')),
            ],
            options={
                'db_table': 'hotel_types',
            },
        ),
        migrations.CreateModel(
            name='CustomersUser',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ', editable=False, length=8, max_length=16, prefix='', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers_users',
            },
        ),
    ]
